# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('issn_number', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('journal_name', models.CharField(max_length=150)),
                ('article_influence', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('est_article_influence', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('is_hybrid', models.BooleanField()),
                ('category', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('update_date', models.DateField()),
                ('journal_issn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Journal')),
            ],
        ),
    ]
