# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160708_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='est_article_influence',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
    ]
