# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160708_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=150)),
                ('journal_issn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Journal')),
            ],
        ),
    ]
