# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 02:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='update_date',
        ),
        migrations.AddField(
            model_name='price',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 13, 2, 15, 28, 630082, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
