# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160713_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='issn_number',
            new_name='issn',
        ),
    ]
