# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160713_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='journal',
        ),
        migrations.AddField(
            model_name='journal',
            name='pub_name',
            field=models.CharField(default='BOOOOOOO', max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
