# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160802_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='time_stamp',
            new_name='date_stamp',
        ),
    ]
