# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160803_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_influence', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('est_article_influence', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('date_stamp', models.DateField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Journal')),
            ],
        ),
    ]
