# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_influence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influence',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='price',
            name='journal',
        ),
        migrations.DeleteModel(
            name='Influence',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
