# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0013_auto_20160803_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_influence', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('est_article_influence', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('date_stamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('issn', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('journal_name', models.CharField(max_length=150)),
                ('pub_name', models.CharField(max_length=150)),
                ('is_hybrid', models.BooleanField()),
                ('category', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_stamp', models.DateField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Journal')),
            ],
        ),
        migrations.AddField(
            model_name='influence',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Journal'),
        ),
    ]
