# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_price_influence'),
    ]

    operations = [
        migrations.AddField(
            model_name='influence',
            name='ai_percentile',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='influence',
            name='cost_effectiveness',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='influence',
            name='ef_percentile',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='influence',
            name='eigenfactor',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
    ]
