# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20160810_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='influence',
            name='efn',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
    ]
