# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-03 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_price_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
